### ISSUE TITLE
Make configurable: selecting the #1 record even when there is no match

### ISSUE THREAD

**Issue by mis306lu** [suranofsky/tech-services-g-sheets-addon#2]

**Comment by lmccoll44** [comment]
Would it be possible to configure it so the record with the most holdings is part the criteria? I was thinking that in the end, I want the record with the most holdings if the ISBN matches, but only if it is for the correct format. Sometimes ISBNs for an ebook are included on a print record and vice versa. So I would rather the result be blank then get a record for the incorrect format.
